spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: servico-service
          uri: lb://servico-service
          predicates:
            - Path=/api/servicos/**
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
